p2: p2.pl
	swipl -O -q -g main --stand_alone=true -o p2 -c p2.pl

p3: p3.pl
	swipl -O -q -g main --stand_alone=true -o p3 -c p3.pl

p4: p4.pl
	swipl -O -q -g main --stand_alone=true -o p4 -c p4.pl

clean:
	rm -rf p2 p3 p4
